services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - '8787:8787'
    command: gunicorn -w 4 -b 0.0.0.0:8787 "src.main:create_face_id_service()"
